// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"goHyper/core/router"
	"goHyper/core/svc"
	"goHyper/core/svc/base"
	"goHyper/internal/api"
	"goHyper/internal/controller/admin"
	"goHyper/internal/controller/example"
	"goHyper/internal/logic"
	"goHyper/internal/model"
)

// Injectors from wire.go:

func InitializeSvc() (*svc.Init, error) {
	config, err := base.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := base.NewLogger(config)
	if err != nil {
		return nil, err
	}
	httpServ, err := svc.NewHttpServ(config, logger)
	if err != nil {
		return nil, err
	}
	modelExample := model.NewExample()
	logicExample := logic.NewExample(modelExample)
	exampleExample := example.NewExample(logicExample)
	apiExample := api.NewExample(exampleExample)
	modelAdmin := model.NewAdmin()
	logicAdmin := logic.NewAdmin(modelAdmin)
	adminAdmin := admin.NewAdmin(logicAdmin)
	apiAdmin := api.NewAdmin(adminAdmin)
	route, err := router.NewRoute(config, logger, apiExample, apiAdmin)
	if err != nil {
		return nil, err
	}
	init, err := svc.NewInit(logger, httpServ, route)
	if err != nil {
		return nil, err
	}
	return init, nil
}
