// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"goHyper/core/router"
	"goHyper/core/svc"
	"goHyper/core/svc/base"
	"goHyper/internal/api/admin"
	"goHyper/internal/controller/admin"
	"goHyper/internal/dao"
	"goHyper/internal/logic"
)

// Injectors from wire.go:

func InitializeSvc() (*svc.Init, error) {
	config, err := base.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := base.NewLogger(config)
	if err != nil {
		return nil, err
	}
	httpServ, err := svc.NewHttpServ(config, logger)
	if err != nil {
		return nil, err
	}
	db, err := base.NewMysql(config, logger)
	if err != nil {
		return nil, err
	}
	admin := dao.NewAdmin(db)
	role := dao.NewRole(db)
	system := logic.NewSystem(admin, role, config)
	ctr_adminSystem := ctr_admin.NewSystem(system)
	route_adminAdmin := route_admin.NewAdmin(ctr_adminSystem)
	route, err := router.NewRoute(config, logger, route_adminAdmin)
	if err != nil {
		return nil, err
	}
	init, err := svc.NewInit(logger, httpServ, route)
	if err != nil {
		return nil, err
	}
	return init, nil
}
